FROM python
WORKDIR /bot
COPY ./ /bot
RUN pip install update
RUN pip install -r requirements.txt




ARG BOT_TOKEN
ARG COSMOSDB_URL
ARG COSMOSDB_KEY

ENV BOT_TOKEN=${BOT_TOKEN}
ENV COSMOSDB_URL=${COSMOSDB_URL}
ENV COSMOSDB_KEY=${COSMOSDB_KEY}
ENV GOOGLE_TOKEN=AIzaSyAWuoSydN7jIKsJxjbQz1sfN8ytN30iTwc
ENV YELP_TOKEN=KJw1YCF5WJzMMwV458YOCd3KRTMhUHjC7SZ5tv24vHKVBWZsDFlm3z9DVyRvtA6_0xMTwnDRUBqPq9od8JVBEp3363UFnvgtKLC0D4pD-FcSuLWvrQvaPgTwcZj4ZXYx

CMD python chatbot.py

