FROM python
WORKDIR /bot
COPY ./ /bot
RUN pip install update
RUN pip install -r requirements.txt




ARG BOT_TOKEN
ARG COSMOSDB_URL
ARG COSMOSDB_KEY

ENV BOT_TOKEN=${BOT_TOKEN}
ENV COSMOSDB_URL=${COSMOSDB_URL}
ENV COSMOSDB_KEY=${COSMOSDB_KEY}
ENV GOOGLE_TOKEN=${GOOGLE_TOKEN}
ENV YELP_TOKEN=${YELP_TOKEN}
ENV BASICURL=${BASICURL}
ENV MODELNAME=${MODELNAME}
ENV APIVERSION=${APIVERSION}
ENV ACCESS_TOKEN=${ACCESS_TOKEN}

CMD python chatbot.py

