name: Deploy to Docker Hub and Azure Container Apps

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: electrow/comp7940_group:latest
        build-args: |
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          COSMOSDB_URL=${{ secrets.COSMOSDB_URL }}
          COSMOSDB_KEY=${{ secrets.COSMOSDB_KEY }}
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp create \
          --name server \
          --resource-group COMP7940-2024 \
          --image electrow/comp7940_group:latest \
          --environment managedEnvironment-COMP79402024-898f \
          --target-port 80 \
          --ingress 'external' \
          --query 'configuration.ingress.fqdn'
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}